export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST'
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS'
export const FETCH_STUDENTS_FAILED = 'FETCH_STUDENTS_FAILED'
export const ADD_NEW_STUDENT_REQUEST = 'ADD_NEW_STUDENT_REQUEST'
export const ADD_NEW_STUDENT_REQUEST_FAILED = 'ADD_NEW_STUDENT_REQUEST_FAILED'
export const ADD_NEW_STUDENT_REQUEST_SUCCESS = 'ADD_NEW_STUDENT_REQUEST_SUCCESS'
export const FILTER_INTERSHIP_STUDENTS = 'FILTER_INTERSHIP_STUDENTS'


